### PR TITLE
 #121 - Using Anserini from Python 

### PR DESCRIPTION
**Pull request by salman1993**
- opened gateway to search with query string and hits to get back a list of document ids
- added docs file to describe the steps

### CODE REVIEW

**Comment by salman1993** [comment]
Added functionality to Python program:
- fetch raw document given docid

**Comment by lintool** [comment]
Can you revert `SearchWebCollection` and copy/paste any code into a new class in the `py4j` package?  

In the current implementation, the Python code directly reaches into multiple Anserini objects (`SearchWebCollection` and `IndexUtils`). I think this will make managing dependencies more complex later down the road. As an alternative, we can have a facade object in the `py4j` namespace that serves as the single point of entry for *all* Python code - even if the code just proxies to other Anserini classes.

I think this will make managing the APIs easier later on.

So it'd look something like this:

```
from py4j.java_gateway import JavaGateway

gateway = JavaGateway()
index = gateway.jvm.java.lang.String("path")
searcher = gateway.jvm.io.anserini.py4j.Pyserini(index)
docids = searcher.search(query_string, num_hits)
doc_text = searcher.getRawDocument(docid)
```

In this case, `Pyserini` is the facade object - and that's the only thing we change as we're building new Python-Java bridge methods.

Thoughts?

**Comment by salman1993** [comment]
what about the search(String query, int hits) method in SearchWebCollection - i should keep that there?

**Comment by lintool** [comment]
no... the reason is that `SearchWebCollection` is due for major refactoring, so I don't want to break anything at this point...

**Comment by salman1993** [comment]
I duplicated the required bits from SearchWebCollection for search(...) and I could use IndexUtils for getRawDocument(...)

**Pull request merged**
